### ISSUE TITLE
Versión con launcher del servidor TR

### ISSUE THREAD

**Issue by latra** [W2Avalanche/streamfiles#2]
Queda pendiente adaptar los layouts de Picks&Bans al servidor TR. Adjunto ejemplo para usarlo a modo máscara
![P B (TR)_CO STREAM](https://github.com/W2Avalanche/streamfiles/assets/17687435/83b966bf-d8f5-49da-a4ca-adc28d312f0a)

**Comment by alfonsomartinde** [comment]
PR creado https://github.com/W2Avalanche/streamfiles/pull/5
