### ISSUE TITLE
Mover CSS de VDO al repo

### ISSUE THREAD

**Issue by alfonsomartinde** [W2Avalanche/streamfiles#3]
Actualizar JSON para que el CSS del VDO sea el del repo, y no el localizado en www.sportiariders.com:

```
https://vdo.ninja/?scene=1&room=w2atv&cover&margin&sl&chroma&s&st&videobitrate=6000&css=https%3A%2F%2Fwww.sportiariders.com%2Fvdo-w2a-ficzone-cams.css
```

**Comment by latra** [comment]
Añadido un css para camaras en dawe y otro para camaras en el momento de "camaras". Falta ver si podemos forzar que en dawe las tres camaras se vean tres en vertical (en lugar de horizontal como hace ahora por resolucion)

**Comment by alfonsomartinde** [comment]
> Añadido un css para camaras en dawe y otro para camaras en el momento de "camaras". Falta ver si podemos forzar que en dawe las tres camaras se vean tres en vertical (en lugar de horizontal como hace ahora por resolucion)

Guay! Lo de las cámaras es algo que está hecho ya. Es simplemente una combinación de 2 parámetros, creo que te lo pasé por Disc

`&cover&916`

![image](https://github.com/W2Avalanche/streamfiles/assets/1211800/19c7b53b-b672-4126-840b-867e724bdd88)

**Comment by latra** [comment]
ack
